apiVersion: v1
kind: Service
metadata:
  name: qa-demo
  namespace: qa-demo
  labels:
    app: qa-demo
spec:
  type: ClusterIP
  selector:
    app: qa-demo
  ports:
    - name: http
      port: 8000
      targetPort: http
